### ISSUE TITLE
RFC: Rework Nitro trap delivery

### ISSUE THREAD

**Issue by tklengyel** [KVM-VMI/kvm#1]
(Just opening this issue to start brainstorming)

As per yesterdays discussion, the following proposal has been made to streamline the delivery of events from KVM to the userspace component. Rather then implementing a get_event() logic to be called by the userspace component for each vCPU, we should introduce a new KVM exit code to be delivered when vcpu_run returns to QEMU (or any other userspace tool driving the VM, like LKVM).

The KVM exit code is delivered via `vcpu->run->exit_reason` when `vcpu_run` returns. This run structure is outlined here http://lxr.free-electrons.com/source/include/uapi/linux/kvm.h#L218. In addition to the exit code, we should add a structure here for VMI specific information to be conveyed.

```
struct {
     __u32 type;
     __u32 flags;
    union {
         struct {
               __u8 direction;
         } nitro;
    };
} vmi;
```

Where `type` can be defined as VMI_NITRO_SYSCALL, VMI_NITRO_SYSENTER and other types of events in the future as we add more (EPT events, MTF, CPUID, etc..).

The `flags` field can be useful for an introspecting application to return a decision on how to handle an event that was trapped. For example in Xen this is used to trigger altp2m switches, trigger MTF or emulation without having to issue a separate call to the VMM.

This will likely need to be wrapped into a CONFIG setting too so that it is conditionally compiled.

RFC!

**Comment by noxdafox** [comment]
Silly question: do we want to keep the NITRO namespace? If so, we might need to check there are no royalties of sort and whether the KVM community will be likely to accept such naming.

We indeed could keep the nitro codename for the project and the module, but maybe rename structures and constant to something more generic such as VMI.

**Comment by smaresca** [comment]
@noxdafox Thanks for the invite - it's much appreciated.

I was thinking about the same naming topic earlier. Unfortunately, I have a feeling the lkml will prefer a more generic name.  We should additionally anticipate questions about overlap with existing kernel profiling facilities like ftrace, systemtap, etc.

The approach @tklengyel has outlined seems sensible to me.

**Comment by noxdafox** [comment]
I think we have to be clear about the Use Case with the lkml. There is plenty of literature supporting it out there @pfohjo's one is the first coming into my mind.

My concern is rather how we get their interest on the thing. I am more afraid will take time to get them into looking at the whole concept as its audience is fairly small.

**Comment by tklengyel** [comment]
I wouldn't worry about convincing lkml about the utility of this addition. We can easily point to Xen and everything that has been built on top of the system that's available there (like https://www.citrix.com/blogs/2016/06/21/a-revolutionary-approach-to-advanced-malware-protection).

Usually as long as the additions make sense and are technologically sound, they won't reject it. Also, Maintainers can't keep things out just because they don't like it or think it has few users. It can be rejected if the patches are not good quality, introduces regressions, etc. That of course doesn't mean they won't request heavy changes and make things hard, but that can be pushed through ;)

**Comment by Wenzel** [comment]
I believe we could close this issue since Nitro is deprecated.
