### ISSUE TITLE
Debian package for Linux kernel

### ISSUE THREAD

**Issue by noxdafox** [KVM-VMI/kvm#2]
We need a Debian package including Nitro's KVM patches in order to help other developers quickly setting up a Nitro capable environment.

Steps:
 * Dowload linux-source debian package: https://packages.debian.org/experimental/linux-source-4.10
 * Apply Nitro patches
 * Follow [this](https://www.debian.org/releases/jessie/i386/ch08s06.html.en) guide.
 * Configure the kernel to be as generic as possible

Using Debian default kernel config:
```
# aptitude download linux-image-4.10
$ dpkg-deb -x linux-image-4.10-amd64.deb ./
$ cp boot/config-4.10-amd64 /path/to/sources/linux/.config
```

**Comment by Wenzel** [comment]
A option is available in the `Vagrantfile` to build debian packages for the kernel, QEMU and libvmi.

Also, another option allows to build a Nitro development environment using these packages.
For now on, they are generated and uploaded manually, hosted on Dropbox.
