### ISSUE TITLE
Add install rule in libkvmi Makefile

### ISSUE THREAD

**Issue by mtarral** [KVM-VMI/kvm#24]
It would be convient to add an `install` rule in [libkvmi's Makefile](https://github.com/KVM-VMI/kvm/blob/kvmi-v6/tools/kvm/kvmi/Makefile), to install the library and headers system-wide.

In my Travis scripts, I have to do the following:
https://github.com/Wenzel/libmicrovmi/blob/master/.travis.yml#L31

~~~YAML
- sudo apt-get install git
- git clone https://github.com/KVM-VMI/kvm --branch kvmi --depth 1
- cd kvm/tools/kvm/kvmi && make && sudo cp -rv include/ /usr/local && sudo cp libkvmi.so /usr/local/lib
~~~

cc @adlazar

Thanks !

**Comment by Wenzel** [comment]
ping @adlazar, do you think you can add a patch in the next kvmi release to deal with this small issue ? :)

**Comment by adlazar** [comment]
Does the above commit help?

**Comment by mtarral** [comment]
@adlazar thanks for the commit.
I will test this and get back to you.

**Comment by Wenzel** [comment]
It works, thanks o/
