### ISSUE TITLE
Git conflicts in files

### ISSUE THREAD

**Issue by aghamir** [KVM-VMI/kvm#6]
There are some conflict in the file that push to the git. For example in kvm_main.c there is:
```
<<<<<<< HEAD

	nitro_create_vm_hook(kvm);

	r = anon_inode_getfd("kvm-vm", &kvm_vm_fops, kvm, O_RDWR | O_CLOEXEC);

	if (r < 0)
=======
	r = get_unused_fd_flags(O_CLOEXEC);
	if (r < 0) {
>>>>>>> linux-vmi

```

**Comment by Wenzel** [comment]
Hi, thanks for the report.

There was indeed some git conflicts which have been pushed to master.

however, i'm not using master at all.
The latest stable vmi modifications are to be found in the `vmi` branch, which is tracked by the git submodule also.

I fixed the conflicts.

**Comment by Soft** [comment]
There is another conflict in https://github.com/KVM-VMI/kvm/blob/master/include/linux/kvm_host.h#L271

**Comment by Wenzel** [comment]
Good find @Soft , i fixed it.
Thanks.
