### ISSUE TITLE
Guest Freeze

### ISSUE THREAD

**Issue by Soft** [KVM-VMI/kvm#9]
KVM patches can cause monitored VMs to freeze.

### Steps to reproduce

Unfortunatelly, the steps to reproduce this problem are little convoluted since they relly on my [multiple backends](https://github.com/Soft/nitro/tree/linux) fork of nitro. I am sure a more minimal test case can be constructed but I've yet to do so. However, asuming the user has setup Nitro:

1. Start executing any of the linux tests: ``nose2 --log-level=debug -v test_linux.TestLinux.test_write``
2. After Nitro has attached to the VM, prematurely terminate the test by pressing ``CTRL-C``
3. Notice the extremely high CPU usage of the VM - the VM is now unresponsive
4. After a while, VM's kernel will [report](https://github.com/KVM-VMI/kvm/files/1204750/crash.txt) the situation.

### Expected Behavior

After terminating the test, the VM should continue execution normally.

---

I haven't really looked into the possible causes of this, but it seems clear that the problem is in the kernel. I am not sure if the problem is present with Windows guests. This problem has been previosly discussed in the [Multiple Backends issue](https://github.com/KVM-VMI/nitro/pull/13)

**Comment by aghamir** [comment]
@Soft Thank you so much for reporting this issue. I've changed the nitro into minimal one that only sends `KVM_NITRO_ATTACH_VM` and `KVM_NITRO_ATTACH_VCPUS` ioctls. Guest freezes in this situation. 
@Wenzel  Do you have any ideas about it?

**Comment by Wenzel** [comment]
Hi,

rom what i read, if you terminate right after nitro has attached and is listening, nitro should detach itself,
which implies to disable the traps.

If you stop nitro too soon, the traps will still be configured, and the VM will be frozen at the next event to be reported.

Nitro is supposed to deal with this (https://github.com/KVM-VMI/nitro/blob/master/nitro/nitro.py#L77)

~~~Python
        self.stop_listen()
        self.kvm_io.close()
~~~

Can you be more specific about when you send the CTRL  C to nitro ?

**Comment by aghamir** [comment]
I've tested `CTRL+C` when events are reporting in userspace:
![image](https://user-images.githubusercontent.com/1880925/29069467-585850f8-7c50-11e7-9043-950a8c02bb0d.png)
After doing `CTRL+C`, I cannot use GVM anymore.
I'm testing this without `CTRL+C` by breaking `for loop` after reporting 10 events. Guest freezes in that situation.
After that I've changed nitro to send only attaches ioctl(without set traps and get event). In that situation we cannot use GVM too.

**Comment by Wenzel** [comment]
hi @aghamir ,

i guess you run `./main.py --stdout <linux_vm_name>`  ?

which is different from running the tests, but anyway.

When you send a CTRL-C, the VM shouldn't stay frozen.
Nitro exits nicely by disabling the traps and continuing the VM execution.

I just tested this on the `master` branch with a `windows 7` vm, and it works.

-> You are on the `linux` branch developped by @Soft  and i didn't verified all those changes yet.
Could you reproduce this on `master` ? (and swithcing to a windows VM)

**Comment by aghamir** [comment]
I test @Soft code on win7x64. It is ok and freezing does not occur in windows. However, `KVM_NITRO_ATTACH_VM` freezes linux GVM. Do you figure out why this happen to linux?

**Comment by aghamir** [comment]
Hi @Wenzel ,
I've noticed that `anon_inode_getfd("kvm-vm", &kvm_vm_fops, kvm, O_RDWR | O_CLOEXEC);`
causes freeze in linux GVM.  
https://github.com/KVM-VMI/kvm/blob/master/virt/kvm/kvm_main.c#L3356
Can you hint me to debug it?

**Comment by Wenzel** [comment]
hi @aghamir 

sorry for the late response.

Do you still have those freezes ?

**Comment by aghamir** [comment]
Hi @Wenzel ,
I am not at upstream. However, I will test it on upstream ASAP.

**Comment by aghamir** [comment]
I test it. Everything is OK now. I didn't find what was the problem. However, your nitro is working perfectly now on ubuntu.

**Comment by Wenzel** [comment]
Great, thanks for the update !
I'm closing this issue.
